fix: ContainsStr FQL to string
fauna/faunadb-js pull request #537
Opened 2021-09-10 12:50 UTC by fireridlle

### Notes
[OSS-888](https://faunadb.atlassian.net/browse/OSS-888)

2021-09-13 15:06 UTC, marrony requested changes
Please, add test for this change

Here is a good place https://github.com/fauna/faunadb-js/blob/main/test/values.test.js#L247

2021-09-23 13:52 UTC, parkhomenko approved these changes

2021-09-24 07:20 UTC, parkhomenko submitted a review, later dismissed

2021-10-04 18:43 UTC, marrony commented on test/query.test.js
> +    expect(Expr.toString(query.ContainsStr('ABC', 'A'))).toEqual(
are we going to move these type of assertions close to the function test? I'm saying because there is a test specific for this case

2021-10-04 18:56 UTC, marrony approved these changes
I liked the fact the expression formatting is close to the function assertions, we could adopt this strategy moving forward (and stop adding more test like this to the `values.tests.js`)

2021-10-04 19:06 UTC, marrony approved these changes
¯\_(ツ)_/¯

2021-10-05 10:30 UTC, merged